config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  
  root 'home#index'
  get 'services', to: 'services#index'
  get 'contact', to: 'contact#index'
  
  get 'about', to: 'contact#about'

  post '/contact', to: 'contact#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
        @contact = Contact.new
    end

    def about
    end
    def new
    end
    def show
    end

      
    def create
        @contact = Contact.new(contact_params)
    
        if @contact.save
        ContactMailer.send_contact_message(@contact).deliver_now
        redirect_to contact_path, notice: 'Message sent successfully!'
        else
        render :index
        end
    end
    
    private
    
    def contact_params
        params.require(:contact).permit(:name, :email, :message)
    end
      
      

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/contact/_contact_form.html.erb
<div class="container mt-5">
  <div class="contact-form-container">
    <%= form_for :contact, url: contact_path do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name, class: 'form-label' %>
            <%= f.text_field :name, class: 'form-control rounded-pill', placeholder: 'Your Name' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :email, class: 'form-label' %>
            <%= f.email_field :email, class: 'form-control rounded-pill', placeholder: 'Your Email' %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :message, class: 'form-label' %>
        <%= f.text_area :message, class: 'form-control rounded', rows: 5, placeholder: 'Your Message' %>
      </div>
      <div class="text-center">
        <%= f.submit 'Send', class: 'btn btn-primary btn-lg rounded-pill' %>
      </div>
    <% end %>
  </div>
</div>

app/views/contact/_contact_modal.html.erb
<turbo-frame id="contact-modal-frame">
  <div class="modal fade" id="contactModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= render "contact_form" %>
      </div>
    </div>
  </div>
</turbo-frame>

app/views/contact/about.html.erb
<!-- app/views/contact/about.html.erb -->

<div class="container mt-5 ">
  <div class="about-container">

    <h2 class="text-center"><strong>A propos de nous</strong> </h2><br>  
    <div class="services-card card mb-4">
      <div class="card mb-4">
        <div class="row no-gutters">
          <div class="col-md-6 d-flex">
            <img src="/assets/about.jpg" alt="Image about page" class="card-img">
          </div>
            
          <div class="col-md-6">
            <div class="card-body">
              <h3 class="card-title">Ecoverde</h3>
              <p class="card-text">Spécialiste de l’architecture paysagère, ECOVERDE Maroc propose des services en création, aménagement et entretien d’espaces verts de tous types. Dédiés aux particuliers et les professionnels (syndics de copropriété, entreprises, promoteurs, collectivités, …) nos artisans vous accompagnent dans vos projets d’aménagements paysagers.</p>
              <p class="card-text">Besoin d’un partenaire privilégié pour la valorisation de vos espaces verts professionnels ou de copropriété, ECOVERDE Maroc est à votre écoute et vous propose une prestation globale, cohérente et de qualité.</p>
            </div>
          </div>
        </div>
      </div>
  </div>  
 </div>  

app/views/contact/index.html.erb
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>
<%= render 'contact_form' %>

app/views/home/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('/assets/home.jpg'); height: 800px;">
  <div class="container">
    <h1>Bienvenue à ECO VERDE</h1>
     <h2><strong>Découvrez tous nos services de jardinage</strong></h2>
    <p>Pour un jardin verdoyant, un gazon jalousé, faites confiance aux jardiniers qualifiés d’ECO VERDE.</p>

    <%= link_to "Contactez nous", contact_path, class:"btn btn-warning" %>
  </div>
</div>

<div class="home d-flex justify-content-center"> <!-- Center-align cards -->
  <div class="card mt-4 mx-2"> <!-- Added mx-2 for horizontal margin --> -->
    <div class="card-body text-center">
      <img src="/assets/approve.png" alt="Image 1" class="card-icon">
      <h3 class="card-title">Prix juste et raisonnable</h3>
      <p class="card-text"></p>
    </div>
  </div>

  <div class="card mt-4 mx-2"> <!-- Added mx-2 for horizontal margin -->
    <div class="card-body text-center">
      <img src="/assets/achievement.png" alt="Image 2" class="card-icon">
      <h3 class="card-title">Rapidité et efficacité</h3>
      <p class="card-text"></p>
    </div>
  </div>

  <div class="card mt-4 mx-2"> <!-- Added mx-2 for horizontal margin -->
    <div class="card-body text-center">
      <img src="/assets/Experience.svg" alt="Image 3" class="card-icon">
      <h3 class="card-title">Expérience et savoir-faire</h3>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecoverde</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= javascript_importmap_tags %>

  
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <footer>
      <%= render 'shared/footer' %>
    </footer>
     
  </body>
</html>
 

app/views/services/index.html.erb
<div class="container mt-5 ">
  <div class="services-container">

    <h2 class="text-center"><strong>Nos Métiers</strong> </h2><br>  
    <div class="services-card card mb-4">
      <div class="card mb-4">
        <div class="row no-gutters">
          <div class="col-md-6 d-flex">
            <img src="/assets/5.jpg" alt="Image 5" class="card-img img-fluid">
          </div>
            
          <div class="col-md-6">
            <div class="card-body">
              <h3 class="card-title">Création et rénovation des jardins</h3>
              <p class="card-text">Que vous souhaitiez réaménager un jardin existant ou créer un jardin paysager de A à Z, à vous de définir l’ambiance dont vous avez envie.</p>
              <p class="card-text">Attentifs et sérieux, nous réalisons une étude personnalisée de votre projet, avant de le concrétiser selon vos souhaits.</p>
              <p class="card-text">Afin de vous permettre de profiter de votre espace vert pendant toute l’année, nous proposons aussi un service d’entretien.</p>
            </div>
          </div>
        </div>
      </div><br>  

      <div class="card mb-4">
            <div class="row no-gutters">
              <div class="col-md-6">
                <div class="card-body">
                  <h3 class="card-title">Entretien des espaces verts</h3>
                  <ul>
                    <li>Taille</li>
                    <li>Désherbage</li>
                    <li>Débroussaillage</li>
                    <li>Élagage des arbres</li>
                    <li>Plantation</li>

                </div>
              </div>
              <div class="col-md-6 d-flex flex-row-reverse">
                <img src="/assets/3.jpg" alt="Image 3" class="card-img img-fluid">
              </div>
            </div>
          </div><br>  


      <div class="card mb-4">
            <div class="row no-gutters">
              <div class="col-md-6 d-flex">
                <img src="/assets/8.jpg" alt="Image 8" class="card-img">
              </div>
                
              <div class="col-md-6">
                <div class="card-body">
                  <h3 class="card-title">Aménagement terrasse</h3>
                  <ul>
                    <li>Montage pergola</li>
                    <li>Nettoyage terrasse</li>
                    <li>Entretien piscine</li>
                  </ul>
                </div>
              </div>
            </div>
      </div>


      <div class="card mb-4">
                        <div class="row no-gutters">
                          <div class="col-md-6">
                            <div class="card-body">
                              <h3 class="card-title">Traitement phytosanitaires</h3>
                              <h3>Traitement phytosanitaires</h3>
                              <p>L'application de produits phytosanitaire peut être requis pour entretenir un jardin ou un espace vert...</p>
                              <p>Les Particuliers: Pour les particuliers nous intervenons dans le traitement des arbres et plantes...</p>
                              <p>Les Professionnels: Collectivités, sociétés, copropriétés, professionnel du jardin, nous intervenons...</p>

                            </div>
                          </div>
                          <div class="col-md-6 d-flex flex-row-reverse">
                            <img src="/assets/10.jpg" alt="Image 10" class="card-img">
                          </div>
                        </div>
      </div><br>  

    
      <div class="card mb-4">
          <div class="row no-gutters">
            <div class="col-md-6 d-flex">
                <img src="/assets/8.jpg" alt="Image 8" class="card-img">
          </div>
          
          <div class="col-md-6">
            <div class="card-body">
              <h3 class="card-title">Installation de système d’arrosage automatique</h3>
              <p>Un système d’arrosage automatique vous permet d’arroser une pelouse à toute heure sans vous fatiguer...</p>
              <p>Pour ce faire, il suffit de le programmer. Pour disposer d’un système d’arrosage automatique fonctionnel et durable, confiez-nous les travaux de mise en place.</p>
            </div>
          </div>
        </div>
      </div> 
    </div> 
  </div>
          
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-contact">
    Ecoverde somewhere <br> Casablanca <br> Tél: 090000000
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> Yakouta/Chadine/Jado
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("logo.png", alt: "Eco Verde Logo", size: "200x100") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(contact_path) %>">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>

        <li class="nav-item <%= 'active' if current_page?(services_path) %>">
          <%= link_to "Services", services_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(contact_path) %>">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
       <li class="nav-item">
         
  </li>

        <!-- ... (other navbar items) -->

          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="accountDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Mon Compte
              </a>
              <div class="dropdown-menu" aria-labelledby="accountDropdown">
                <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class:"navbar-item, btn btn-warning" %>
              <%= link_to "Sign up", new_user_registration_path, class:"navbar-item, btn btn-warning"%>
            </li>
          <% end %>

<!-- ... (other navbar items) -->

      </ul>
    </div>
  </div>

</div>